### ISSUE TITLE
newChildColor is not working

### ISSUE THREAD

**Issue by Duke1014** [learn-co-curriculum/react-hooks-information-flow-code-along#1] opened 2021-08-13 18:38 UTC
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/3532/assignments/124154?module_item_id=255835

## Describe the bug

In Deliverables Part 2, newChildColor is throwing an error: src/Parent.js
  Line 6:38:  'newChildColor' is not defined  no-undef

There's no way to currently see the expected result.

## What is the expected behavior?

The page should load with no errors.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ X ] WSL
- [ ] Linux

**Comment by lizbur10** [comment] 2021-08-17 15:30
Hi there!

I'm not able to reproduce this issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Closed as completed by lizbur10** 2021-08-17 15:30 UTC
Labels: bug
